version: '3'

services:

    app:
        build: .
        container_name: "nest_api"
        entrypoint: ./.docker/entrypoint.sh
        container_name: nest-api
        # environment: 
        #   - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:3000
        volumes:
            - .:/home/node/app

    mysql:
        container_name: "nest_mysql"
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: on-failure:2
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/dbdata:/var/lib/mysql"        
        environment:
            MYSQL_DATABASE: nest_api
            MYSQL_ROOT_PASSWORD: 102030 
            MYSQL_USER: root
            MYSQL_PASSWORD: 102030      